name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild clean -workspace ./Example/VSKit.xcworkspace -scheme VSKit-Example
           xcodebuild build -workspace ./Example/VSKit.xcworkspace -scheme VSKit-Example
           xcodebuild -workspace ./Example/VSKit.xcworkspace -scheme VSKit-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.4' test | xcpretty
